#!/usr/bin/env node

const buildTool = require('./buildTool');
const remoteBuild = require('./remoteBuild');
const process = require('process');


const args = process.argv;


if (args.length > 2){
   remoteBuild.buildApp(args[2]);
} else {
    buildTool.build();
}